services:
  mysql:
    image: elestio/mysql:8.0
    restart: always
    hostname: mysql
    volumes:
      - ./storage/mysql:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      glpi-mysql:
        ipv4_address: 172.10.0.3

  glpi:
    image: elestio/glpi:latest
    restart: always
    hostname: glpi
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./storage/var/www/html/glpi/:/var/www/html/glpi
      - ./apache/php.ini:/etc/php/8.1/apache2/php.ini
    environment:
      - TIMEZONE=America/Sao_Paulo
    networks:
      glpi-mysql:
        ipv4_address: 172.10.0.4

networks:
  glpi-mysql:
    ipam:
      config:
        - subnet: "172.10.0.0/16"
